name: Build Android APK (No Wrapper)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Gradle manually
        run: |
          sudo apt-get update
          sudo apt-get install -y gradle
          gradle -v

      - name: Build APK using system Gradle
        run: |
          echo "Building APK using system gradle"
          gradle assembleDebug --stacktrace || gradle build --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: hk-arrival-tracker-apk
          path: app/build/outputs/apk/debug/*.apk
