name: Android APK Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build debug APK
        run: |
          unzip hk_arrival_tracker_project.zip -d project
          cd project/hk_arrival_tracker_project/app
          ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: HK_Arrival_Tracker
          path: project/hk_arrival_tracker_project/app/build/outputs/apk/debug/app-debug.apk
