name: Build HK Arrival Tracker from Zip

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Unzip project
        run: |
          mkdir project
          unzip hk_arrival_tracker_project.zip -d project

      - name: Build debug APK
        run: |
          cd project/hk_arrival_tracker_project/app
          chmod +x ./gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: HK_Arrival_Tracker
          path: project/hk_arrival_tracker_project/app/build/outputs/apk/debug/app-debug.apk
